SELECT SYSDATE FROM DUAL;

SELECT SYSDATE+10 FROM DUAL;

SELECT SYSDATE-10 FROM DUAL;

SELECT TO_CHAR(SYSDATE, ‘MM-DD-YYYY HH:MI:SS’) “NOW” FROM DUAL;


SELECT ADD_MONTHS(SYSDATE, 2) FROM DUAL;

SELECT ADD_MONTHS(SYSDATE,-2) FROM DUAL;


SELECT LAST_DAY(SYSDATE) FROM DUAL;

SELECT SYSDATE, LAST_DAY(SYSDATE) "Last", LAST_DAY(SYSDATE) - SYSDATE "Days Left" FROM DUAL;


SELECT NEXT_DAY(SYSDATE,'MONDAY') FROM DUAL;

SELECT NEXT_DAY(SYSDATE,’FRIDAY’) FROM DUAL;


SELECT MONTHS_BETWEEN(’05-JAN-81′,’05-JAN-80′) FROM DUAL;

SELECT MONTHS_BETWEEN(’05-JAN-80′,’05-JAN-81′) FROM DUAL;


LTER SESSION SET NLS_DATE_FORMAT = ‘DD-MON-YYYY HH24:MI:SS’;

SELECT CURRENT_DATE, SESSIONTIMEZONE FROM DUAL;

ALTER SESSION SET TIME_ZONE = ‘-2:0’;

SELECT CURRENT_DATE, SESSIONTIMEZONE FROM DUAL;