--------------------------------------------------------
--  File created - Friday-August-04-2023   
--------------------------------------------------------
DROP TABLE "ADMIN"."EMP";
--------------------------------------------------------
--  DDL for Table EMP
--------------------------------------------------------

  CREATE TABLE "ADMIN"."EMP" 
   (	"ID" NUMBER(*,0), 
	"NAME" VARCHAR2(15), 
	"DEPARTMENTID" NUMBER(*,0), 
	"SALARY" NUMBER(8,2), 
	"GENDER" VARCHAR2(10), 
	"AGE" NUMBER(*,0), 
	"CITY" VARCHAR2(10), 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "ADMIN"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "ADMIN"
REM INSERTING into ADMIN.EMP
SET DEFINE OFF;
Insert into ADMIN.EMP (ID,NAME,DEPARTMENTID,SALARY,GENDER,AGE,CITY) values (1001,'John',10,35350,'Male',25,'London');
Insert into ADMIN.EMP (ID,NAME,DEPARTMENTID,SALARY,GENDER,AGE,CITY) values (1002,'Smith',20,45450,'Female',27,'Mumbai');
Insert into ADMIN.EMP (ID,NAME,DEPARTMENTID,SALARY,GENDER,AGE,CITY) values (1003,'James',30,50550,'Male',28,'Delhi');
Insert into ADMIN.EMP (ID,NAME,DEPARTMENTID,SALARY,GENDER,AGE,CITY) values (1004,'Mike',30,50000,'Male',28,'London');
Insert into ADMIN.EMP (ID,NAME,DEPARTMENTID,SALARY,GENDER,AGE,CITY) values (1005,'Linda',20,75000,'Female',26,'Mumbai');
Insert into ADMIN.EMP (ID,NAME,DEPARTMENTID,SALARY,GENDER,AGE,CITY) values (1006,'Anurag',10,35000,'Male',25,'London');
Insert into ADMIN.EMP (ID,NAME,DEPARTMENTID,SALARY,GENDER,AGE,CITY) values (1007,'Priyanla',20,45000,'Female',27,'Mumbai');
Insert into ADMIN.EMP (ID,NAME,DEPARTMENTID,SALARY,GENDER,AGE,CITY) values (1008,'Sambit',10,50000,'Male',28,'London');
Insert into ADMIN.EMP (ID,NAME,DEPARTMENTID,SALARY,GENDER,AGE,CITY) values (1009,'Pranaya',10,50000,'Male',28,'London');
Insert into ADMIN.EMP (ID,NAME,DEPARTMENTID,SALARY,GENDER,AGE,CITY) values (1010,'Hina',20,75000,'Female',26,'Mumbai');
--------------------------------------------------------
--  Constraints for Table EMP
--------------------------------------------------------

  ALTER TABLE "ADMIN"."EMP" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "ADMIN"  ENABLE
